sudo: true
language: haskell

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"

matrix:
  include:
  - ghc: 8.8.2
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.8.2.yaml"
    
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.8.3.yaml"

  - ghc: 8.10.1

before_install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal update
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
    fi
install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal build --enable-tests --enable-benchmarks
    else
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options='-Werror'
    fi
script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test --enable-tests
    else
      stack test --system-ghc
    fi
