name:                ghc-clippy-plugin
version:             0.0.0.1
github:              "ArturGajowy/ghc-clippy-plugin"
license:             BSD3
author:              "Artur Gajowy"
maintainer:          "artur.gajowy@gmail.com"
copyright:           "2020 Artur Gajowy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Override GHC error messages to the user's liking
category:            Development, Compiler Plugin

description:         Please see the README on GitHub at <https://github.com/ArturGajowy/ghc-clippy-plugin#readme>

dependencies:
- base               >= 4.7 && < 5
- ghc                >= 8.8.2 && < 8.11
- text               >= 1.2.3.2 && < 1.3
- text-icu           >= 0.7.0 && < 0.8
- text-regex-replace >= 0.1.1 && < 0.2
- dhall              >= 1.30.0 && < 1.33

library:
  source-dirs: src

ghc-options:
- -fobject-code
- -Wall
